# -*- coding: utf-8 -*-
"""Fama-Macbeth sample code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZlLJ6PPkQ6jX66PkpKP7wbTipDxg4tU
"""

#!pip install pykrx

import pandas as pd
import numpy as np
import statsmodels.api as sm
from pykrx import stock
from tqdm import tqdm

"""
Fama-Macbeth sample code

Noah Son
blog: https://blog.naver.com/athran_zala
email: quantson@kaist.ac.kr

Fama-Macbeth 설명: https://blog.naver.com/athran_zala/222696535672
코드 설명: https://blog.naver.com/athran_zala/222732550775

이 코드에서의 목적

1. CAPM beta가 주가 수익률에 대한 설명력이 있는가?
2. Size, Book-to-market이 주가 수익률에 대한 설명력이 있는가?


Caution:
계산의 편의를 위해 2010-01-02부터 2022-04-30까지 코스피/코스닥에 생존한 주식 중 임의의 n개 기업을 대상으로만 분석을 실시함.
정확한 분석을 위해선 생존 편향(Survivorship bias)을 고려하기 위해 해당 기간에 상장폐지된 기업도 분석 대상으로 포함해야 함.
"""

date_start = "20100102"
date_end = "20220430"

company_df_start = stock.get_market_ohlcv(date_start, market="ALL")
company_df_end = stock.get_market_ohlcv(date_end, market="ALL")

ticker_list = list(set(company_df_start.index) & set(company_df_end.index))

len(ticker_list)

# 월간 가격 및 재무데이터 얻기

n = 100

data_list = []

for tic in tqdm(ticker_list[:n]):
  close = stock.get_market_ohlcv(date_start, date_end, tic, "m")['종가']
  mkt_cap = stock.get_market_cap(date_start, date_end, tic, "m")

  # 모든 재무데이터가 0인 케이스인 경우 혹은 재무데이터 자체가 없을 경우 이 주식을 분석대상에서 제외
  try:
    account = stock.get_market_fundamental(
        date_start, date_end, tic, "m")[['BPS', 'PER', 'PBR', 'EPS']]\
        .replace(0, np.nan).dropna(how='all')

  except KeyError:
    continue

  if len(account) == len(close):

    concated_df = pd.concat([close, mkt_cap, account], axis=1).reset_index()
    concated_df['ticker'] = tic
    concated_df.set_index(['ticker', '날짜'], inplace=True)

    data_list.append(concated_df)

  else:
    pass

data = pd.concat(data_list).reset_index()

data.head()

data['ticker'].unique().shape

mkt_close = stock.get_index_ohlcv("19960101", date_end, "1001", 'm')['종가'] # 코스피지수

price = data.pivot_table(index='날짜', columns='ticker', values='종가')
monthly_rtn = price.diff(1).divide(price.shift(1).replace(0, np.nan), axis=0).dropna(how='all')
mkt_rtn = mkt_close.diff(1).divide(mkt_close.shift(1), axis=0).loc[monthly_rtn.index]
mkt_cap = data.pivot_table(index='날짜', columns='ticker', values='시가총액').loc[monthly_rtn.index]
pbr = data.pivot_table(index='날짜', columns='ticker', values='PBR').loc[monthly_rtn.index]
bm = 1/pbr[pbr>0] #book-to-market = 1/PBR

"""# CAPM

$R_{i,t}-R_{f,t}=\alpha_{i}+\beta_{i,t}(R_{m,t}-R_{f,t})+\varepsilon_{i,t}$

### 편의상 $R_{f,t}=0$
"""

# 5년(최소 3년 이상의 데이터) 롤링을 통해 CAPM 베타 구하기


def get_beta(stock_rtn, mkt_port_rtn):
  x = sm.add_constant(mkt_port_rtn.loc[stock_rtn.index])
  model = sm.OLS(stock_rtn, x).fit()
  #model = sm.OLS(stock_rtn, x).fit(cov_type='HAC', cov_kwds={'maxlags':12}) #Newey-West estimator

  return model.params.values[1]


capm_beta = monthly_rtn.rolling(12*5, min_periods=12*3)\
      .apply(lambda each_stock_rtn: get_beta(each_stock_rtn, mkt_rtn)).dropna(how='all')

capm_beta.head()

"""## 1. CAPM beta가 주가 수익률에 대해 설명력을 보이는가?

### Fama and Macbeth (1973) 분석의 단순한 버전

## $R_{i,t}-R_{f,t}=\gamma_{0,t} + \gamma_{1,t} \beta_{i,t} + \epsilon_{i,t}$


### Step 1: 매 시점 $t$마다 cross-section regression을 통해 $\gamma_{0,t}$, $\gamma_{1,t}$ 추정

### Step 2: 이렇게 추정한 $\gamma_{1,t}$의 time-series 평균, 표준편차 및 t-stat을 구함

### Step 3: t-stat의 절댓값이 2 이상이면($E(\gamma_{1,t})\neq 0$) CAPM beta가 주가 수익률에 대한 설명력이 있다고 판단
"""

# Step 1

def get_gamma_1(rtn, beta):
  beta = beta.loc[rtn.name].dropna() # t시점의 개별 주식의 베타만 필요함
  idx = list(set(rtn.dropna().index) & set(beta.index)) # 수익률 및 베타 데이터가 모두 있는 주식들만 선별

  rtn = rtn.loc[idx]
  beta = sm.add_constant(beta.loc[idx])

  model = sm.OLS(rtn, beta).fit()

  return model.params.values[1] # gamma_1만 리턴


gamma_1_df = monthly_rtn.loc[capm_beta.index].apply(lambda cross_sec_rtn: get_gamma_1(cross_sec_rtn, capm_beta), axis=1)

gamma_1_df.head()

# Step 2

# trick: y = a*1 + e로 식을 구성하고 회귀분석을 돌리면 a는 y의 평균이 됨


model = sm.OLS(gamma_1_df, np.ones(len(gamma_1_df))).fit()

gamma_1_df.mean()

# Step 3
model.summary()

# t=1.859 이므로 이 데이터셋에서는 설명력이 없어보임.

"""## 2. Size, Book-to-Market이 주가 수익률에 대해 설명력을 보이는가?

### $R_{i,t}-R_{f,t}=\gamma_{0,t} + \gamma_{1,t} \beta_{i,t}  + \gamma_{2,t} \log(SIZE_{i,t})  + \gamma_{3,t} \log(BM_{i,t}) + \epsilon_{i,t}$

"""

# Step 1

def get_gamma_list(rtn, beta, ln_size, ln_bm):
  # t시점의 개별 주식의 베타, size, bm만 필요함

  beta = beta.loc[rtn.name]
  size = ln_size.loc[rtn.name]
  bm = ln_bm.loc[rtn.name]

  x_df = sm.add_constant(pd.concat([beta, size, bm], axis=1)).dropna()
  idx = list(set(rtn.dropna().index) & set(x_df.index)) # 데이터가 모두 있는 주식들만 선별

  rtn = rtn.loc[idx]
  x_df = x_df.loc[idx]

  model = sm.OLS(rtn, x_df).fit()

  return model.params.values[1:] # gamma_1, gamma_2, gamma_3만 리턴


gamma_df = monthly_rtn.loc[capm_beta.index]\
                            .apply(lambda cross_sec_rtn:
                                  get_gamma_list(cross_sec_rtn, capm_beta,
                                                  np.log(mkt_cap[mkt_cap > 0]),
                                                  np.log(bm[bm > 0])), axis=1)

gamma_df = monthly_rtn.loc[capm_beta.index]\
                            .apply(lambda cross_sec_rtn:
                                  get_gamma_list(cross_sec_rtn, capm_beta,
                                                  np.log(mkt_cap[mkt_cap > 0]),
                                                  np.log(bm[bm > 0])), axis=1)

#Step 2

model_gamma1 = sm.OLS(gamma_df.apply(lambda x: x[0]), np.ones(len(gamma_df))).fit()
model_gamma2 = sm.OLS(gamma_df.apply(lambda x: x[1]), np.ones(len(gamma_df))).fit()
model_gamma3 = sm.OLS(gamma_df.apply(lambda x: x[2]), np.ones(len(gamma_df))).fit()

#Step 3

model_gamma1.summary()

# size, bm을 통제변수로 추가했을 때 베타의 설명력은 더욱 감소함 (t=1.488)

model_gamma2.summary()

# size는 이 데이터셋에서 주가 수익률을 설명하는 것처럼 보임(t=3.502)

model_gamma3.summary()

# Book-to-market은 이 데이터셋에서 설명력이 없음 (t=0.759)

